# Site settings
title: Mnmlst Dvlpr
author: Stefan Oehme
email: st.oehme@gmail.com
description: Minimalist, vegan, independent software developer.
baseurl: ""
url: "https://oehme.github.io"
github_username:  oehme
twitter_username: StefanOehme

# Build settings
markdown: kramdown
kramdown:
  input: GFM
theme: minima
plugins:
  - jekyll-feed

permalink: /:categories/:title
show_excerpts: true
