# Site settings
title: Mnmlst Dvlpr
email: st.oehme@gmail.com
description: > 
  A blog about developing software
  as well as myself.
baseurl: ""
url: "http://http://oehme.github.io"
twitter_username: StefanOehme
github_username:  oehme

# Build settings
markdown: redcarpet
pygments_options: ['lineanchors', 'linenos=table']
