# Site settings
title: Mnmlst Dvlpr
author: Stefan Oehme
email: st.oehme@gmail.com
description: Minimalist, vegan, Gradle core team lead.
baseurl: ""
url: "https://oehme.github.io"
github_username:  oehme

# Build settings
markdown: kramdown
kramdown:
  input: GFM
theme: minima
plugins:
  - jekyll-feed
  - jekyll-analytics

permalink: /:categories/:title
show_excerpts: true

jekyll_analytics:
  GoogleAnalytics:
    id: UA-20206101-2
